### ISSUE TITLE
Volume Namen aus Clustern ableiten

### ISSUE THREAD

**Issue by olant** [olant/synergy-ansible#1]
Die Volume-Namen müssen aus den Cluster-Namen abgeleitet werden statt aus der Tabelle direkt ausgelesen zu werden.
Pro Cluster zwei Volumes, Name: Clustername+0001/0002
https://github.com/olant/synergy-ansible/blob/4a09220d66e281ff3d82923e3c9425f3d1968391/feste-script/convert.py#L2420

**Comment by k3x** [comment]
@olant 

- Bitte testen
- ggf Synergy-Nimble zeile 29 entfernen oder ändern

**Comment by olant** [comment]
Geändert
