### ISSUE TITLE
Provide information how to change line 1218

### ISSUE THREAD

**Issue by k3x** [olant/synergy-ansible#8]
`outfile.write('      name: "Nublar_EG_3e"'+"\n") #CODE gleicher Name wie in enclosuregroup`

**Comment by olant** [comment]
Aus Synergy-MGMT Zeile 34. Alle Vorkommen "Nublar_EG_3e" müssen als Variable referenziert werden.

**Comment by k3x** [comment]
in der ehemaligen 08 Zeile 1131 ist "Nublar_EG_3e" hardcoded...

**Comment by k3x** [comment]
Ich schreibe in der Zeile im Ersten Beitrag jetzt den Wert aus der Excel B23/E34. Meintest du das?

**Comment by olant** [comment]
> Ich schreibe in der Zeile im Ersten Beitrag jetzt den Wert aus der Excel B23/E34. Meintest du das?

B34/E34 - ja. In allen Modulen dann pls
